name: ACHIEVE-Service-CICD-docker

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
          - DEV
          - QA
          - UAT

jobs:
  build-and-deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, qa-test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t image2 .
          docker save -o image2.tar image2:latest

      - name: Docker Swarm Deployment
        run: |
          cd "C:\Users\amardeep.kini\demo"
          docker stack deploy -c demo.yaml demo-app
