name: dynamic-submission-web-v1

on:
  push: 
    branches: [ demo-3]
    tags:
      - 'dev*'
      - 'uat*'
      - 'prod*'
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        description: Select Environment
        options:
          - DEV
          - UAT
          - PROD

jobs:  
  build:
    name: Build and Deploy Angular Project
    runs-on: self-hosted

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i -f

      - name: Building project
        run: ng build

      - name: Determine Environment
        id: env
        run: |
          TAG="${{ github.ref }}"
          if ($TAG -like "refs/tags/dev*") {
            Write-Output "::set-output name=env::DEV"
          } elseif ($TAG -like "refs/tags/uat*") {
            Write-Output "::set-output name=env::UAT"
          } elseif ($TAG -like "refs/tags/prod*") {
            Write-Output "::set-output name=env::PROD"
          } else {
            Write-Output "Invalid tag format"
            exit 1
          }


      - name: Deploy
        run: |
          ENV=${{ steps.env.outputs.env }}

          if [ "$ENV" == "DEV" ]; then
            # Deployment to DEV
            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
          elif [ "$ENV" == "UAT" ]; then
            # Deployment to UAT
            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
          elif [ "$ENV" == "PROD" ]; then
            # Deployment to PROD
            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
          else
            echo "Invalid environment"
            exit 1
          fi
