name: Trigger on push and pull requests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
        - DEV
        - QA
        - UAT
     
  create:
    tags:
      - '*.*'


     
jobs:  
  build:
    name: Build and Deploy Angular Project
    runs-on: self-hosted

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i -f

      - name: Building project
        run: ng build

      
      - name: Deploy to DEV
        if: ${{ github.event.inputs.environment == 'dev'}}
        run: |
          Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
          Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
          # Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 

      - name: Deploy to QA
        if: ${{ github.event.inputs.environment == 'QA'}}
        run: |
          Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
          Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
          Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 

      - name: Deploy to UAT
        if: ${{ github.event.inputs.environment == 'UAT'}}
        run: |
          Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
          Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
          Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 


      # - name: Copying from dist to IIS folder
      #   run: |      
      #     Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
      #     Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
      #     Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 

      
