name: dynamic-submission-web-v1

on:
  push:
    tags:
      - '*.*'
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        description: Select Environment
        options:
          - DEV
          - QA
          - UAT

jobs:  
  build:
    name: Build and Deploy Angular Project
    runs-on: self-hosted

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i -f

      - name: Building project
        run: ng build

      - name: Determine Environment
        id: env
        run: echo "::set-output name=env::${{ github.event.inputs.environment }}"

      - name: Deploy
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV=${{ steps.env.outputs.env }}
          else
            # Extract environment from the tag name
            ENV=$(echo "${{ github.ref }}" | cut -d '/' -f 3)
          fi

          if [ "$ENV" == "DEV" ]; then
            # Deployment to DEV
            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
          elif [ "$ENV" == "QA" ]; then
            # Deployment to QA
            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
          elif [ "$ENV" == "UAT" ]; then
            # Deployment to UAT
            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
          else
            echo "Invalid environment"
            exit 1
          fi
