name: ACHIEVE-UI-CICD

on:
  push:
    branches:
      - '**'
    tags:
      - 'dev_v*' 
      - 'uat_v*'  
      - 'prod_v*'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
          - DEV
          - QA
          - UAT

jobs:
  build-and-test:
    name: Build and Deploy Angular Project
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i -f

      - name: Building project
        run: ng build --base-href=/achieve/

     

  another-job:
    name: Deployment Job
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
       - name: Determine Environment
         id: env
         if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
         run: |
          Write-Output "Event Name: $env:GITHUB_EVENT_NAME"
          Write-Output "Ref: $env:GITHUB_REF"
          if ($env:GITHUB_EVENT_NAME -eq 'workflow_dispatch') {
            Write-Output "::set-output name=env::${{ github.event.inputs.environment }}"

          } elseif ($env:GITHUB_REF -match '^refs/tags/') {
          $TAG = $env:GITHUB_REF
          Write-Output "Tag: $TAG"
          if ($TAG -match '^refs/tags/dev_v*') {
            $ENV = "DEV"
            echo "$ENV"
            Write-Output "::set-output name=env::$ENV"
          } elseif ($TAG -match '^refs/tags/uat_v*') {
            $ENV = "UAT"
            Write-Output "Environment: $ENV"
            Write-Output "::set-output name=env::$ENV"
          } elseif ($TAG -match '^refs/tags/prod_v*') {
            $ENV = "QA"
            Write-Output "::set-output name=env::$ENV"
          }
          }

          Write-Output "ENV: $ENV"

       - name: Deploy
         if: success()
         run: |
               $ENV = "${{ steps.env.outputs.env }}"
               echo "Environment: $ENV"
               if ($ENV -eq "DEV") {
                  ng build --base-href=/achieve/
                  Get-ChildItem -Path "C:\new-test-01-dev" | Remove-Item -Recurse -Force
                  Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "C:\new-test-01-dev" -Recurse -Force
               } elseif ($ENV -eq "QA") {
                  Get-ChildItem -Path "C:\new-test-01-dev" | Remove-Item -Recurse -Force
                  Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "C:\new-test-01-dev" -Recurse -Force
               } elseif ($ENV -eq "UAT") {
                   Get-ChildItem -Path "C:\new-test-01-dev" | Remove-Item -Recurse -Force
                  Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "C:\new-test-01-dev" -Recurse -Force
               } else {
                  Write-Output "Invalid environment"
                  exit 1
               }
