name: Delete Files and Directories

on:
  push:
    branches:
      - '**'

jobs:
  delete_files_and_directories: 
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete files and directories
        run: |
          Set-Location -Path "C:\power-hcm-demo"
          Get-ChildItem -File -Recurse | Where-Object { $_.DirectoryName -notmatch "\\(achieve|engage|attendence|paywheel)\\*" } | Remove-Item -Force
          Get-ChildItem -Directory -Recurse | Where-Object { $_.FullName -notmatch "\\(achieve|engage|attendence|paywheel)\\*" -and @(Get-ChildItem -Path $_.FullName -Recurse).Count -eq 0 } | Remove-Item -Force -Recurse
